"""create photography tables

Revision ID: a6b1a7fcdd52
Revises: fb04eda95c9c
Create Date: 2026-07-29 15:31:52.157518
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a6b1a7fcdd52"
down_revision: str | None = "fb04eda95c9c"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "photography_photos",
        sa.Column("sha256_hash", sa.String(length=64), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("source_path", sa.Text(), nullable=False),
        sa.Column("original_relpath", sa.String(length=500), nullable=False),
        sa.Column("thumbnail_relpath", sa.String(length=500), nullable=False),
        sa.Column("preview_relpath", sa.String(length=500), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("file_size_bytes", sa.Integer(), nullable=False),
        sa.Column("rotation_degrees", sa.Integer(), nullable=False),
        sa.Column("caption", sa.Text(), nullable=True),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("exif_json", sa.Text(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_photography_photos_sha256_hash"),
        "photography_photos",
        ["sha256_hash"],
        unique=True,
    )
    op.create_table(
        "photography_photo_relationships",
        sa.Column("photo_id", sa.String(), nullable=False),
        sa.Column("entity_type", sa.String(length=60), nullable=False),
        sa.Column("entity_id", sa.String(length=36), nullable=False),
        sa.Column("is_hero", sa.Boolean(), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["photo_id"], ["photography_photos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_photography_photo_relationships_entity_id"),
        "photography_photo_relationships",
        ["entity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_photography_photo_relationships_entity_type"),
        "photography_photo_relationships",
        ["entity_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_photography_photo_relationships_photo_id"),
        "photography_photo_relationships",
        ["photo_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_photography_photo_relationships_photo_id"),
        table_name="photography_photo_relationships",
    )
    op.drop_index(
        op.f("ix_photography_photo_relationships_entity_type"),
        table_name="photography_photo_relationships",
    )
    op.drop_index(
        op.f("ix_photography_photo_relationships_entity_id"),
        table_name="photography_photo_relationships",
    )
    op.drop_table("photography_photo_relationships")
    op.drop_index(op.f("ix_photography_photos_sha256_hash"), table_name="photography_photos")
    op.drop_table("photography_photos")
    # ### end Alembic commands ###
