"""create kit_library_kits table

Revision ID: d19bdb22e52f
Revises:
Create Date: 2026-07-29 11:03:10.215964
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "d19bdb22e52f"
down_revision: str | None = None
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "kit_library_kits",
        sa.Column("manufacturer", sa.String(length=120), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("grade", sa.String(length=40), nullable=False),
        sa.Column("scale", sa.String(length=20), nullable=True),
        sa.Column("mobile_suit_designation", sa.String(length=80), nullable=True),
        sa.Column("product_number", sa.String(length=60), nullable=True),
        sa.Column("series", sa.String(length=120), nullable=True),
        sa.Column("release_year", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("difficulty_estimate", sa.Integer(), nullable=True),
        sa.Column("estimated_build_hours", sa.Float(), nullable=True),
        sa.Column("purchase_date", sa.Date(), nullable=True),
        sa.Column("purchase_price_cents", sa.Integer(), nullable=True),
        sa.Column("storage_location", sa.String(length=120), nullable=True),
        sa.Column("tags_csv", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("kit_library_kits")
    # ### end Alembic commands ###
