"""create build_planner tables

Revision ID: fb04eda95c9c
Revises: d19bdb22e52f
Create Date: 2026-07-29 12:15:32.357423
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "fb04eda95c9c"
down_revision: str | None = "d19bdb22e52f"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "build_planner_projects",
        sa.Column("kit_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("template_key", sa.String(length=60), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("is_commission", sa.Boolean(), nullable=False),
        sa.Column("progress_override_percent", sa.Integer(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_build_planner_projects_kit_id"), "build_planner_projects", ["kit_id"], unique=False
    )
    op.create_table(
        "build_planner_stages",
        sa.Column("build_project_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("weight", sa.Integer(), nullable=False),
        sa.Column("is_completed", sa.Boolean(), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["build_project_id"], ["build_planner_projects.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_build_planner_stages_build_project_id"),
        "build_planner_stages",
        ["build_project_id"],
        unique=False,
    )
    op.create_table(
        "build_planner_journal_entries",
        sa.Column("build_project_id", sa.String(), nullable=False),
        sa.Column("build_stage_id", sa.String(), nullable=True),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["build_project_id"], ["build_planner_projects.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["build_stage_id"], ["build_planner_stages.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_build_planner_journal_entries_build_project_id"),
        "build_planner_journal_entries",
        ["build_project_id"],
        unique=False,
    )
    op.create_table(
        "build_planner_tasks",
        sa.Column("build_stage_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("is_completed", sa.Boolean(), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("estimated_hours", sa.Float(), nullable=True),
        sa.Column("actual_hours", sa.Float(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["build_stage_id"], ["build_planner_stages.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_build_planner_tasks_build_stage_id"),
        "build_planner_tasks",
        ["build_stage_id"],
        unique=False,
    )
    op.create_table(
        "build_planner_work_sessions",
        sa.Column("build_project_id", sa.String(), nullable=False),
        sa.Column("build_stage_id", sa.String(), nullable=True),
        sa.Column("build_task_id", sa.String(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("paused_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("paused_seconds", sa.Integer(), nullable=False),
        sa.Column("is_billable", sa.Boolean(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["build_project_id"], ["build_planner_projects.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["build_stage_id"], ["build_planner_stages.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["build_task_id"], ["build_planner_tasks.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_build_planner_work_sessions_build_project_id"),
        "build_planner_work_sessions",
        ["build_project_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_build_planner_work_sessions_build_project_id"),
        table_name="build_planner_work_sessions",
    )
    op.drop_table("build_planner_work_sessions")
    op.drop_index(op.f("ix_build_planner_tasks_build_stage_id"), table_name="build_planner_tasks")
    op.drop_table("build_planner_tasks")
    op.drop_index(
        op.f("ix_build_planner_journal_entries_build_project_id"),
        table_name="build_planner_journal_entries",
    )
    op.drop_table("build_planner_journal_entries")
    op.drop_index(
        op.f("ix_build_planner_stages_build_project_id"), table_name="build_planner_stages"
    )
    op.drop_table("build_planner_stages")
    op.drop_index(op.f("ix_build_planner_projects_kit_id"), table_name="build_planner_projects")
    op.drop_table("build_planner_projects")
    # ### end Alembic commands ###
